### ISSUE TITLE
Not able to parse <html> tags.

### ISSUE THREAD

**Issue by ashish235** [hbokh/dashing-icinga#3]
Hi,

While starting the docker by passing the CGI URL of my ICINGA, I do not get any data on the dashboards. On checking the logs, I can see it renders the whole page starting the below exception. 

scheduler caught exception:
757: unexpected token at '<html>

And ending at. 

</html>
'
/var/lib/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
/var/lib/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in`parse'
/dashing/jobs/icinga.rb:119:in `request_status'
/dashing/jobs/icinga.rb:192:in`get_status_host'
/dashing/jobs/icinga.rb:26:in `block in <top (required)>'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in`call'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in`block in trigger'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in`block in trigger_job'

A quick help would be appreciated.

Thanks.

**Comment by hbokh** [comment]
Cannot reproduce, sorry... And I am no way any good in Ruby.

**Comment by ashish235** [comment]
@hbokh, can you help me with the ICINGA config, I think I did some mistake there. Any links for configuration or something?

**Comment by hbokh** [comment]
Check [https://www.icinga.org/resources/docs/](Icinga docs).
FYI I run this against an Icinga v1 instance, where `ICINGA_CGI=https://icinga-hostname/icinga/cgi-bin/status.cgi`.

**Comment by ashish235** [comment]
I figured it out, issue was with ICINGA which couldn't export the data in json format.
